name: CI/CD
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the docker image
        run: |
          docker build -f ./Dockerfile -t ${{ secrets.DOCKER_USER }}/message-cannon-homolog:latest --no-cache .
      - name: Docker push
        run: docker push ${{ secrets.DOCKER_USER }}/message-cannon-homolog:latest
